### ISSUE TITLE
DB Update requires documentation

### ISSUE THREAD

**Issue by cartogram** [cartogram/landing#1]
@Petahhh I have no idea how the DB update script works, can you add it to the Read me

**Comment by Petahhh** [comment]
I've commented the script and I hope it helps you understand the specifics of what goes on to make it work.

The readme file has been updated with a succinct explanation of what it does. 

I've also described the steps required to use the updater in a comment at the top of the file.

I've also renamed it to dbupdate.php which I thought was a better name choice because it is easier to remember.
